# fly.toml app configuration file generated for paris-app on 2023-07-12T20:40:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "paris-app"
primary_region = "ewr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "npm run migrate up"
